name: plannusandroidversion
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.6
  firebase_storage: ^3.1.6
  firebase_auth: ^0.16.0
  provider: ^4.1.2
  flutter_spinkit: ^4.1.2
  google_sign_in: ^4.4.6
  bottom_navy_bar: ^5.4.0
  shared_preferences: ^0.5.7+2
  intl: ^0.16.1
  moor_flutter: ^1.6.0
  shimmer: ^1.1.1
  google_fonts: ^1.1.0
  flutter_slidable: ^0.5.3
  image_picker: ^0.6.7
  flushbar: ^1.10.4
  json_annotation:
  firebase_messaging: ^6.0.16
  timer_builder: ^1.3.0
  get_it: ^4.0.2
  flutter_local_notifications: ^1.4.4+1
  timetable: ^0.2.4
  time_machine: ^0.9.12
  google_maps_flutter: ^0.5.28+1
  location: ^3.0.2
  geolocator: ^5.3.2+2
  geocoder: ^0.2.1
  flutter_google_places: ^0.2.5
  dio: ^3.0.9
  uuid: ^2.2.0
  image_cropper: ^1.2.3
  cached_network_image: ^2.2.0+1
  flutter_rating_bar: ^3.0.1+1
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: ^4.1.1
  rxdart:
  build_runner:
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/planNUS.png
    - assets/profilepicture.png
    - assets/google.jpg
    - assets/plannusupgraded.png
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
